language: node_js
node_js: 
    - 14.15.0

cache: npm

install: 
    - npm install

before_script: chmod 0777 ./node_modules/.bin/mocha

script: 
    - npm test

after_script: npm run coverage

deploy: 
    provider: pages
    draft: true
    skip-cleanup: true
    github_tpken: $GITHUB_TOKEN #6a9e02855ea7eace51db3aeb8a78a87e153db518
    edge: true
    local_dir: build
    on:
        branch: master

notification:
    - email: false