language: node_js
node_js: 
    - 14.15.1

cache: npm

install: 
    - npm install

before_script: chmod 0777 ./node_modules/.bin/mocha

script: npm test

after_script: npm run coverage

# deploy: 
#     provider: pages
#     skip-cleanup: true
#     github_token: $GITHUB_TOKEN
#     edge: true
#     local_dir: build
#     on:
#         branch: master

notification:
    email: false